config/routes.rb
Rails.application.routes.draw do
  get 'site/index'

  devise_for :users
  resources :donations

  root 'site#index'
    get '/signup', to: 'users/SIGN_UP'

end

app/models/donation.rb
class Donation < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

         has_many :bookmarks 
         belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params)

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url, notice: 'Donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:title, :dondate, :donstatus, :donaddress, :doncity)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  
def index
    # retrieve all Bookmarks ordered by descending creation timestamp
    @donations = Donation.order('created_at desc')
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/donations/_form.html.erb
<%= form_for(@donation) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :dondate %><br>
    <%= f.datetime_select :dondate %>
  </div>
  <div class="field">
    <%= f.label :donstatus %><br>
    <%= f.check_box :donstatus %>
  </div>
  <div class="field">
    <%= f.label :donaddress %><br>
    <%= f.text_field :donaddress %>
  </div>
  <div class="field">
    <%= f.label :doncity %><br>
    <%= f.text_field :doncity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing Donation</h1>

<%= render 'form' %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Donations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Dondate</th>
      <th>Donstatus</th>
      <th>Donaddress</th>
      <th>Doncity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= donation.title %></td>
        <td><%= donation.dondate %></td>
        <td><%= donation.donstatus %></td>
        <td><%= donation.donaddress %></td>
        <td><%= donation.doncity %></td>
        <td><%= link_to 'Show', donation %></td>
        <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
        <td><%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Donation', new_donation_path %>

app/views/donations/new.html.erb
<h1>New Donation</h1>

<%= render 'form' %>

<%= link_to 'Back', donations_path %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @donation.title %>
</p>

<p>
  <strong>Dondate:</strong>
  <%= @donation.dondate %>
</p>

<p>
  <strong>Donstatus:</strong>
  <%= @donation.donstatus %>
</p>

<p>
  <strong>Donaddress:</strong>
  <%= @donation.donaddress %>
</p>

<p>
  <strong>Doncity:</strong>
  <%= @donation.doncity %>
</p>

<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Donations</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/site/index.html.erb
<h1>Upcoming Donations</h1>

<br/>
<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
<%= link_to "Sign Up" %>
<%= link_to "Sign In" %>
<h2>Latest Donations</h2>
<table style="width: 100%">
  <thead>
    <tr>
      <th>Donation List</th>
    </tr>
  </thead>

  <tbody>
  <% @donations.each do |donation| %>
    <tr>
      <td><%= link_to donation.title %></td>
    </tr>
  <% end %>
  </tbody>
</table>